# Generated by Django 2.2.6 on 2019-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('inicio_cta', models.DateField(auto_now_add=True)),
                ('actualizacion_cta', models.DateField(auto_now=True)),
            ],
        ),
    ]
