# Generated by Django 2.2.6 on 2019-12-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_aor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuariox',
        ),
    ]
