# Generated by Django 2.2.6 on 2019-12-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20191206_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xuser',
            new_name='Usuario',
        ),
    ]
