# Generated by Django 2.2.6 on 2020-01-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0014_auto_20200103_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_gdp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_planta',
        ),
        migrations.DeleteModel(
            name='Gdp',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
