# Generated by Django 2.2.6 on 2020-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0015_auto_20200109_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='Estandar',
            field=models.ManyToManyField(to='seguridad.Estandar'),
        ),
    ]
