# Generated by Django 2.2.6 on 2020-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0016_proceso_estandar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='Estandar',
        ),
        migrations.AddField(
            model_name='estandar',
            name='idproceso',
            field=models.ManyToManyField(to='seguridad.Proceso'),
        ),
    ]
