# Generated by Django 2.2.6 on 2020-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0019_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
