# Generated by Django 2.2.6 on 2019-12-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_auto_20191205_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
