# Generated by Django 2.2.6 on 2019-12-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20191206_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('id_estandar', models.CharField(max_length=30)),
            ],
        ),
    ]
